# URL | Recursive (y/n)
https://codeberg.org/Gourieff/comfyui-reactor-node.git|n
https://github.com/chflame163/ComfyUI_LayerStyle.git|n
https://github.com/chrisgoringe/cg-image-picker.git|n
https://github.com/chrisgoringe/cg-use-everywhere.git|n
https://github.com/cubiq/ComfyUI_essentials.git|n
https://github.com/Enemyx-net/VibeVoice-ComfyUI.git|n
https://github.com/Fannovel16/comfyui_controlnet_aux.git|n
https://github.com/Fannovel16/ComfyUI-Frame-Interpolation.git|n
https://github.com/Fictiverse/ComfyUI_Fictiverse.git|n
https://github.com/flowtyone/ComfyUI-Flowty-LDSR.git|n
https://github.com/GACLove/ComfyUI-VFI.git|n
https://github.com/Jordach/comfy-plasma.git|n
https://github.com/JPS-GER/ComfyUI_JPS-Nodes.git|n
https://github.com/kijai/ComfyUI-CogVideoXWrapper.git|n
https://github.com/kijai/ComfyUI-Florence2.git|n
https://github.com/kijai/ComfyUI-KJNodes.git|n
https://github.com/kijai/ComfyUI-MelBandRoFormer.git|n
https://github.com/kijai/ComfyUI-segment-anything-2.git|n
https://github.com/kijai/ComfyUI-SUPIR.git|n
https://github.com/kijai/ComfyUI-WanVideoWrapper.git|n
https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git|n
https://github.com/Lightricks/ComfyUI-LTXVideo.git|n
https://github.com/ltdrdata/ComfyUI-Impact-Pack.git|n
https://github.com/ltdrdata/ComfyUI-Impact-Subpack|n
https://github.com/ltdrdata/ComfyUI-Manager.git|n
https://github.com/MoonGoblinDev/Civicomfy.git|n
https://github.com/PowerHouseMan/ComfyUI-AdvancedLivePortrait.git|n
https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git|n
https://github.com/rgthree/rgthree-comfy.git|n
https://github.com/shadowcz007/comfyui-mixlab-nodes.git|n
https://github.com/ssitu/ComfyUI_UltimateSDUpscale|y
https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes.git|n
https://github.com/theUpsider/ComfyUI-Logic.git|n
https://github.com/WASasquatch/was-node-suite-comfyui.git|n
https://github.com/XLabs-AI/x-flux-comfyui.git|n
https://github.com/yolain/ComfyUI-Easy-Use.git|n
